# docker compose file
services:

  postgres:
    image: postgres:17
    container_name: roster-postgres

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: roster_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: roster-backend

    environment:
      DATABASE_URL: postgresql+psycopg://postgres:password@postgres:5432/roster_db
      PYTHONPATH: /app

    ports:
      - "8000:8000"

    volumes:
      - ./backend:/app

    depends_on:
      - postgres

  frontend:
    build: ./frontend
    container_name: roster-frontend

    ports:
      - "5173:5173"

    volumes:
      - ./frontend:/app
      - /app/node_modules

    depends_on:
      - backend
      
volumes:
  postgres_data: