"""Remove display order uniqueness

Revision ID: d7a1b24c255b
Revises: e4e759ba2dab
Create Date: 2026-08-15 11:42:19.553336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7a1b24c255b'
down_revision: Union[str, Sequence[str], None] = 'e4e759ba2dab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('team_members_display_order_key'), 'team_members', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('team_members_display_order_key'), 'team_members', ['display_order'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
