"""Create roster database tables

Revision ID: e4e759ba2dab
Revises: 
Create Date: 2026-08-15 10:20:09.746835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e4e759ba2dab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rosters',
    sa.Column('roster_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('roster_name', sa.String(length=100), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('group_number', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('roster_id'),
    sa.UniqueConstraint('roster_name'),
    sa.UniqueConstraint('year', 'month', name='uq_roster_year_month')
    )
    op.create_table('team_members',
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('employee_id'),
    sa.UniqueConstraint('display_order')
    )
    op.create_table('roster_assignments',
    sa.Column('roster_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('shift', sa.String(length=2), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['team_members.employee_id'], ),
    sa.ForeignKeyConstraint(['roster_id'], ['rosters.roster_id'], ),
    sa.PrimaryKeyConstraint('roster_id', 'employee_id', 'date')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('roster_assignments')
    op.drop_table('team_members')
    op.drop_table('rosters')
    # ### end Alembic commands ###
